changelog:
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: New Features 🎉
      labels:
        - enhancement
    - title: Bug Fixes 🐛
      labels:
        - bug
    - title: Documentation 📚
      labels:
        - documentation
    - title: Dependency Updates ⛓️
      labels:
        - dependencies
    - title: Maintenance 🔧
      labels:
        - chore
    - title: Other Changes
      labels:
        - "*"
