import { Reminder } from "model/reminder";
import { DateTime } from "model/time";
import {
  NTFY_SEQUENCE_ID_PREFIX,
  assignSequenceIds,
  computeSequenceId,
  isObsidianReminderSequenceId,
} from "./sequence-id";

function makeReminder(
  file: string,
  title: string,
  rowNumber: number,
): Reminder {
  return new Reminder(
    file,
    title,
    DateTime.parse("2021-09-08 09:00"),
    rowNumber,
    false,
  );
}

describe("computeSequenceId()", (): void => {
  test("only uses characters allowed by ntfy's sequence ID pattern and stays within 64 characters", (): void => {
    const id = computeSequenceId("Notes/Todo.md", "Buy 牛乳 🥛 & more!", 3);
    expect(id).toMatch(/^[-_A-Za-z0-9]{1,64}$/);
  });

  test("always starts with the plugin's prefix", (): void => {
    const id = computeSequenceId("Todo.md", "Task", 0);
    expect(id.startsWith(NTFY_SEQUENCE_ID_PREFIX)).toBe(true);
  });

  test("is deterministic for the same file and title", (): void => {
    const id1 = computeSequenceId("Todo.md", "Task 1", 0);
    const id2 = computeSequenceId("Todo.md", "Task 1", 0);
    expect(id1).toBe(id2);
  });

  test("differs for different titles", (): void => {
    const id1 = computeSequenceId("Todo.md", "Task 1", 0);
    const id2 = computeSequenceId("Todo.md", "Task 2", 0);
    expect(id1).not.toBe(id2);
  });

  test("differs for different files", (): void => {
    const id1 = computeSequenceId("A.md", "Task", 0);
    const id2 = computeSequenceId("B.md", "Task", 0);
    expect(id1).not.toBe(id2);
  });

  test("differs by index", (): void => {
    const id0 = computeSequenceId("Todo.md", "Task", 0);
    const id1 = computeSequenceId("Todo.md", "Task", 1);
    expect(id0).not.toBe(id1);
  });

  test("does not collide when file/title characters could be redistributed across the boundary", (): void => {
    // With a plain space as the join separator, file="a" + title="b c" and
    // file="a b" + title="c" would both hash the same string ("a b c").
    const id1 = computeSequenceId("a", "b c", 0);
    const id2 = computeSequenceId("a b", "c", 0);
    expect(id1).not.toBe(id2);
  });
});

describe("isObsidianReminderSequenceId()", (): void => {
  test("recognizes IDs generated by this plugin", (): void => {
    expect(
      isObsidianReminderSequenceId(computeSequenceId("A.md", "T", 0)),
    ).toBe(true);
  });

  test("rejects IDs from other apps", (): void => {
    expect(isObsidianReminderSequenceId("some-other-app-id")).toBe(false);
  });
});

describe("assignSequenceIds()", (): void => {
  test("gives duplicate (file, title) reminders distinct sequence IDs", (): void => {
    const r1 = makeReminder("Todo.md", "Water plants", 2);
    const r2 = makeReminder("Todo.md", "Water plants", 5);
    const ids = assignSequenceIds([r1, r2]);
    expect(ids.get(r1)).not.toBe(ids.get(r2));
  });

  test("assigns the same IDs regardless of input order (row-number order wins)", (): void => {
    const r1 = makeReminder("Todo.md", "Water plants", 2);
    const r2 = makeReminder("Todo.md", "Water plants", 5);
    const idsForward = assignSequenceIds([r1, r2]);
    const idsReversed = assignSequenceIds([r2, r1]);
    expect(idsForward.get(r1)).toBe(idsReversed.get(r1));
    expect(idsForward.get(r2)).toBe(idsReversed.get(r2));
    // The earlier row number (r1) gets index 0, i.e. the ID with no suffix.
    expect(idsForward.get(r1)).toBe(
      computeSequenceId("Todo.md", "Water plants", 0),
    );
    expect(idsForward.get(r2)).toBe(
      computeSequenceId("Todo.md", "Water plants", 1),
    );
  });

  test("does not confuse reminders with the same title in different files", (): void => {
    const r1 = makeReminder("A.md", "Task", 0);
    const r2 = makeReminder("B.md", "Task", 0);
    const ids = assignSequenceIds([r1, r2]);
    expect(ids.get(r1)).toBe(computeSequenceId("A.md", "Task", 0));
    expect(ids.get(r2)).toBe(computeSequenceId("B.md", "Task", 0));
  });

  test("leaves non-duplicate reminders at index 0", (): void => {
    const r1 = makeReminder("A.md", "Task 1", 0);
    const r2 = makeReminder("A.md", "Task 2", 1);
    const ids = assignSequenceIds([r1, r2]);
    expect(ids.get(r1)).toBe(computeSequenceId("A.md", "Task 1", 0));
    expect(ids.get(r2)).toBe(computeSequenceId("A.md", "Task 2", 0));
  });
});
