import type { Reminder } from "model/reminder";

/**
 * Prefix for every sequence ID this plugin generates. ntfy topics can be
 * shared by multiple apps/devices publishing scheduled messages, so the sync
 * logic (`computeNtfySyncPlan`) must be able to tell "our" scheduled
 * messages apart from anyone else's and never touch (in particular, never
 * delete) a scheduled message it didn't create.
 */
export const NTFY_SEQUENCE_ID_PREFIX = "obr-";

/** Whether `id` was generated by this plugin (see `NTFY_SEQUENCE_ID_PREFIX`). */
export function isObsidianReminderSequenceId(id: string): boolean {
  return id.startsWith(NTFY_SEQUENCE_ID_PREFIX);
}

// Two unrelated 32-bit FNV-1a offset-basis constants. Hashing the same input
// once per constant and concatenating the results (base36) gives a compact,
// crypto-free fingerprint wide enough that collisions between the small
// number of reminders in a single vault are not a practical concern.
const FNV_PRIME = 0x01000193;
const FNV_OFFSET_BASIS_1 = 0x811c9dc5;
const FNV_OFFSET_BASIS_2 = 0x9e3779b9;

function fnv1a(input: string, offsetBasis: number): number {
  let hash = offsetBasis;
  for (let i = 0; i < input.length; i++) {
    hash ^= input.charCodeAt(i);
    hash = Math.imul(hash, FNV_PRIME);
  }
  return hash >>> 0;
}

// Both `file` and `title` are always single-line strings (a vault path and a
// reminder title parsed from one line of Markdown, respectively), so a
// newline can never appear in either. Joining them with "\n" therefore makes
// `hashKey()` collision-free between the two fields: unlike a plain space
// (or any other printable separator), there's no way to redistribute
// characters across the boundary and get the same joined string, e.g.
// file="a", title="b c" vs. file="a b", title="c" no longer collide.
const FIELD_SEPARATOR = "\n";

function hashKey(file: string, title: string): string {
  return `${file}${FIELD_SEPARATOR}${title}`;
}

/**
 * Deterministically derives an ntfy sequence ID from a reminder's `file` and
 * `title`. Sequence IDs must match ntfy's `^[-_A-Za-z0-9]{1,64}$`, and
 * publishing again under the same ID replaces a still-pending scheduled
 * message on the server instead of creating a duplicate (see
 * `computeNtfySyncPlan`).
 *
 * The reminder's time is deliberately excluded from the ID: changing a
 * reminder's time (including snoozing it) must resolve to the *same* ID, so
 * republishing replaces the old schedule rather than leaving a stale
 * duplicate behind on the server.
 *
 * `index` disambiguates reminders that share the same `file` and `title`
 * (see `assignSequenceIds`); pass `0` for the first (and usually only) one.
 */
export function computeSequenceId(
  file: string,
  title: string,
  index: number,
): string {
  const key = hashKey(file, title);
  const h1 = fnv1a(key, FNV_OFFSET_BASIS_1).toString(36);
  const h2 = fnv1a(key, FNV_OFFSET_BASIS_2).toString(36);
  const id = `${NTFY_SEQUENCE_ID_PREFIX}${h1}${h2}`;
  return index === 0 ? id : `${id}-${index}`;
}

/**
 * Assigns a sequence ID to every reminder in `reminders`, disambiguating
 * reminders that share the same `file` + `title` with a deterministic index
 * (0, 1, 2, ...). The index is derived by sorting a copy of `reminders` by
 * file path, then row number, so every device computes the same assignment
 * for the same vault state regardless of the order `reminders` was passed
 * in.
 */
export function assignSequenceIds(
  reminders: ReadonlyArray<Reminder>,
): Map<Reminder, string> {
  const sorted = [...reminders].sort((a, b) => {
    if (a.file !== b.file) {
      return a.file < b.file ? -1 : 1;
    }
    return a.rowNumber - b.rowNumber;
  });

  const nextIndexByKey = new Map<string, number>();
  const result = new Map<Reminder, string>();
  for (const reminder of sorted) {
    const key = hashKey(reminder.file, reminder.title);
    const index = nextIndexByKey.get(key) ?? 0;
    nextIndexByKey.set(key, index + 1);
    result.set(
      reminder,
      computeSequenceId(reminder.file, reminder.title, index),
    );
  }
  return result;
}
