name: Build plugin

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "*.*.*" # Push events to matching any tag format, i.e. 1.0, 20.15.10
      - "!*.*.*-beta*"

env:
  PLUGIN_NAME: obsidian-reminder

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check if the tag commit is contained in master branch
        run: |
          if ! git merge-base --is-ancestor ${{ github.ref }} master; then
            echo "Tag commit is not contained in master branch"
            exit 1
          fi
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x" # You might need to adjust this value to your own version
      - name: Build
        id: build
        run: |
          npm ci
          npm run build
          mkdir ${{ env.PLUGIN_NAME }}
          cp main.js manifest.json styles.css ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false
          files: |
            ${{ env.PLUGIN_NAME }}.zip
            main.js
            manifest.json
            styles.css
