name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version of the plugin e.g. 1.0.0"
        required: true

env:
  PLUGIN_NAME: obsidian-reminder

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: 'Setup jq'
        uses: dcarbone/install-jq-action@v2.1.0
      - name: Update the versions
        run: |
          MINIMUM_OBSIDIAN_VERSION=1.0.3
          version=${{ github.event.inputs.version }}
          echo "RELEASE_VERSION=$version" >> $GITHUB_ENV
          
          # update manifest version
          sed -i "s/\"version\": \".*\"/\"version\": \"$version\"/" manifest.json
          jq --arg key "$version" --arg value "$MINIMUM_OBSIDIAN_VERSION" '. + { ($key): $value }' "versions.json" > tmp.json && mv tmp.json "versions.json"

          # commit and push the changes
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add manifest.json versions.json
          git commit -m "Update the version to $version"
          git push origin master
          git tag $version
          git push --tags
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x" # You might need to adjust this value to your own version
      - name: Build
        id: build
        run: |
          npm ci
          npm run build
          mkdir ${{ env.PLUGIN_NAME }}
          cp main.js manifest.json styles.css ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          name: ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false
          files: |
            ${{ env.PLUGIN_NAME }}.zip
            main.js
            manifest.json
            styles.css
